import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next & Tailwind - Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p className="text-3xl p-4 text-violet-600 hover:text-violet-900 hover:font-bold">
          <a
            href="https://tailwindcss.com/blog/tailwindcss-v3-1"
            target="_blank"
            rel="noreferrer"
          >
            Tailwind 3.2.1
          </a>
        </p>
        <p className="text-3xl p-4 text-violet-600 hover:text-violet-900 hover:font-bold">
          <a
            href="https://nextjs.org/blog/next-12-1"
            target="_blank"
            rel="noreferrer"
          >
            Next JS 12.1
          </a>
        </p>
        <p className="text-3xl p-4 text-violet-600 hover:text-violet-900 hover:font-bold">
          <a
            href="https://nextjs.org/blog/next-12-1"
            target="_blank"
            rel="noreferrer"
          >
            React 18.2.0
          </a>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
